
-- DO NOT MODIFY THIS FILE !!!

function GameRoom:SetupUIObjects()
   self.game_room = self:GetStaticImageFromXML(168)
   self.ready_btn = self:GetButtonFromXML(9)
   self.map_btn = self:GetButtonFromXML(10)
   self.map_view = self:GetStaticImageFromXML(28)
   self.room_name = self:GetTextFromXML(29)
   self.user_status1 = self:GetStaticImageFromXML(30)
   self.user_status2 = self:GetStaticImageFromXML(31)
   self.user_status3 = self:GetStaticImageFromXML(32)
   self.user_status4 = self:GetStaticImageFromXML(33)
   self.textlist1 = self:GetTextListFromXML(34)
   self.text1 = self:GetTextFromXML(35)
   self.group2 = self:GetGroupFromXML(36)
   self.radiobutton7 = self:GetRadioButtonFromXML(17)
   self.radiobutton6 = self:GetRadioButtonFromXML(16)
   self.radiobutton5 = self:GetRadioButtonFromXML(15)
   self.radiobutton4 = self:GetRadioButtonFromXML(14)
   self.radiobutton3 = self:GetRadioButtonFromXML(13)
   self.radiobutton2 = self:GetRadioButtonFromXML(12)
   self.radiobutton1 = self:GetRadioButtonFromXML(11)
   self.user_level1 = self:GetStaticImageFromXML(37)
   self.user_level3 = self:GetStaticImageFromXML(38)
   self.user_level2 = self:GetStaticImageFromXML(39)
   self.user_level4 = self:GetStaticImageFromXML(40)
   self.user_major1 = self:GetStaticImageFromXML(41)
   self.user_major2 = self:GetStaticImageFromXML(42)
   self.user_major3 = self:GetStaticImageFromXML(43)
   self.user_major4 = self:GetStaticImageFromXML(44)
   self.user_ready1 = self:GetStaticImageFromXML(45)
   self.user_ready2 = self:GetStaticImageFromXML(46)
   self.user_ready3 = self:GetStaticImageFromXML(47)
   self.user_ready4 = self:GetStaticImageFromXML(48)
   self.snake_kind1 = self:GetStaticImageFromXML(50)
   self.snake_kind2 = self:GetStaticImageFromXML(51)
   self.snake_kind3 = self:GetStaticImageFromXML(52)
   self.snake_kind4 = self:GetStaticImageFromXML(53)
   self.exit_btn = self:GetButtonFromXML(56)
   self.snake_random = self:GetRadioButtonFromXML(18)
   self.snake7 = self:GetRadioButtonFromXML(23)
   self.snake6 = self:GetRadioButtonFromXML(24)
   self.snake5 = self:GetRadioButtonFromXML(25)
   self.snake4 = self:GetRadioButtonFromXML(22)
   self.snake3 = self:GetRadioButtonFromXML(21)
   self.snake2 = self:GetRadioButtonFromXML(20)
   self.snake1 = self:GetRadioButtonFromXML(19)
   self.how_btn = self:GetButtonFromXML(136)
   self.credit_btn = self:GetButtonFromXML(137)
   self.bgm_btn = self:GetCheckBoxFromXML(175)
   self.es_btn = self:GetCheckBoxFromXML(176)

   self.group2:AddChild(self.radiobutton7)
   self.group2:AddChild(self.radiobutton6)
   self.group2:AddChild(self.radiobutton5)
   self.group2:AddChild(self.radiobutton4)
   self.group2:AddChild(self.radiobutton3)
   self.group2:AddChild(self.radiobutton2)
   self.group2:AddChild(self.radiobutton1)
end
