
-- DO NOT MODIFY THIS FILE !!!

function SnakeScene:SetupUIObjects()
   self.game_window = self:GetStaticImageFromXML(6)
   self.game_user_status1 = self:GetStaticImageFromXML(57)
   self.game_user_status2 = self:GetStaticImageFromXML(58)
   self.game_user_status3 = self:GetStaticImageFromXML(59)
   self.game_user_status4 = self:GetStaticImageFromXML(60)
   self.game_user_status5 = self:GetStaticImageFromXML(61)
   self.big_red_ball = self:GetStaticImageFromXML(64)
   self.big_yellow_ball = self:GetStaticImageFromXML(65)
   self.big_green_ball = self:GetStaticImageFromXML(66)
   self.big_blue_ball = self:GetStaticImageFromXML(67)
   self.big_black_ball = self:GetStaticImageFromXML(68)
   self.big_grey_ball = self:GetStaticImageFromXML(69)
   self.big_white_ball = self:GetStaticImageFromXML(70)
   self.small_red_ball1 = self:GetStaticImageFromXML(71)
   self.small_yellow_ball1 = self:GetStaticImageFromXML(72)
   self.small_green_ball1 = self:GetStaticImageFromXML(73)
   self.small_blue_ball1 = self:GetStaticImageFromXML(74)
   self.small_black_ball1 = self:GetStaticImageFromXML(75)
   self.small_grey_ball1 = self:GetStaticImageFromXML(76)
   self.small_white_ball1 = self:GetStaticImageFromXML(77)
   self.small_red_ball2 = self:GetStaticImageFromXML(88)
   self.small_yellow_ball2 = self:GetStaticImageFromXML(90)
   self.small_green_ball2 = self:GetStaticImageFromXML(92)
   self.small_blue_ball2 = self:GetStaticImageFromXML(94)
   self.small_black_ball2 = self:GetStaticImageFromXML(95)
   self.small_grey_ball2 = self:GetStaticImageFromXML(96)
   self.small_white_ball2 = self:GetStaticImageFromXML(97)
   self.small_red_ball3 = self:GetStaticImageFromXML(98)
   self.small_yellow_ball3 = self:GetStaticImageFromXML(99)
   self.small_green_ball3 = self:GetStaticImageFromXML(102)
   self.small_blue_ball3 = self:GetStaticImageFromXML(103)
   self.small_black_ball3 = self:GetStaticImageFromXML(104)
   self.small_grey_ball3 = self:GetStaticImageFromXML(105)
   self.small_white_ball3 = self:GetStaticImageFromXML(106)
   self.game_snake1 = self:GetStaticImageFromXML(107)
   self.game_snake2 = self:GetStaticImageFromXML(108)
   self.game_snake3 = self:GetStaticImageFromXML(109)
   self.game_snake4 = self:GetStaticImageFromXML(110)
   self.game_snake5 = self:GetStaticImageFromXML(111)
   self.major1 = self:GetStaticImageFromXML(112)
   self.major2 = self:GetStaticImageFromXML(113)
   self.major3 = self:GetStaticImageFromXML(114)
   self.major4 = self:GetStaticImageFromXML(115)
   self.major5 = self:GetStaticImageFromXML(116)
   self.level1 = self:GetStaticImageFromXML(117)
   self.level2 = self:GetStaticImageFromXML(118)
   self.level3 = self:GetStaticImageFromXML(119)
   self.level4 = self:GetStaticImageFromXML(120)
   self.level5 = self:GetStaticImageFromXML(121)
   self.user_id1 = self:GetTextFromXML(122)
   self.user_id2 = self:GetTextFromXML(123)
   self.user_id3 = self:GetTextFromXML(124)
   self.user_id4 = self:GetTextFromXML(125)
   self.user_id5 = self:GetTextFromXML(126)
   self.map_name = self:GetTextFromXML(127)
   self.message = self:GetStaticImageFromXML(128)
   self.time = self:GetImageNumberFromXML(129)

end
